matrix:
  include:
    - name: Linux
      sudo: true
      os: linux
      dist: xenial
      before_script:
      - sudo apt-get purge mysql*

    - name: OSX
      sudo: true
      os: osx
      osx_image: xcode10.1

install: true

script:
  - ./init.sh
