matrix:
  include:
    - name: Linux
      sudo: true
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - dirmngr
      before_script:
      - sudo apt-get purge mysql*

    - name: OSX
      sudo: true
      os: osx
      osx_image: xcode10.1
      before_script:
      - brew uninstall --force gpg2
      - brew uninstall --force python3
      - brew uninstall --force wget

install: true

script:
  - ./init.sh
