matrix:
  include:
    - name: Linux
      sudo: true
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - dirmngr
      before_script:
      - sudo apt-get purge mysql*
      - sudo apt-get purge python*

    - name: OSX
      sudo: true
      os: osx
      osx_image: xcode10.1

install: true

script:
  - ./init.sh
