tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "coreutils"
brew "fish"
brew "fzf"
brew "git-flow"
brew "htop"
brew "neovim"
brew "python"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "unrar"
brew "vim", args: ["with-override-system-vi"]
brew "watchman"
brew "wget"
brew "yarn", args: ["without-node"]
cask "atom"
cask "flux"
cask "iterm2"
cask "spotify"
cask "visual-studio-code"
