#!/usr/bin/env fish

set changed_files (git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)

if contains 'Brewfile' $changed_files; and test $IS_OSX -eq 1
  brew bundle --global
end

if contains 'dpkg.list' $changed_files; and test $IS_LINUX -eq 1
  sudo dpkg --set-selections < ~/.dpkg.list
end

if contains '.gitmodules' $changed_files
  git submodule update --init --recursive
end

