-- lazy.nvim
return {
  -- "folke/snacks.nvim",
  -- ---@type snacks.Config
  -- opts = {
  --   picker = {},
  --   explorer = {},
  -- },
  -- keys = {
  --   -- Top Pickers & Explorer
  --   {
  --     "<leader><space>",
  --     function()
  --       Snacks.picker.smart()
  --     end,
  --     desc = "Smart Find Files",
  --   },
  --   {
  --     "<leader>fg",
  --     function()
  --       Snacks.picker.grep()
  --     end,
  --     desc = "Grep",
  --   },
  --   {
  --     "<leader>fG",
  --     function()
  --       Snacks.picker.grep({ hidden = true })
  --     end,
  --     desc = "Grep hidden",
  --   },
  --   {
  --     "<leader>fgg",
  --     function()
  --       Snacks.picker.grep({ ignored = true })
  --     end,
  --     desc = "Grep ignored",
  --   },
  --   -- find
  --   {
  --     "<leader>fc",
  --     function()
  --       Snacks.picker.files({ cwd = vim.fn.stdpath("config") })
  --     end,
  --     desc = "Find Config File",
  --   },
  --   {
  --     "<leader>fb",
  --     function()
  --       Snacks.picker.buffers({ sort_lastused = true, current = false })
  --     end,
  --     desc = "Find Buffers",
  --   },
  --   {
  --     "<leader>ff",
  --     function()
  --       Snacks.picker.files()
  --     end,
  --     desc = "Find Files",
  --   },
  --   {
  --     "<leader>FF",
  --     function()
  --       Snacks.picker.files({ hidden = true })
  --     end,
  --     desc = "Find Files",
  --   },
  --   {
  --     "<leader>fp",
  --     function()
  --       Snacks.picker.projects({
  --         dev = { "~/workspace/github/", "~/workspace/work/" },
  --         patterns = { ".git" },
  --         recent = true,
  --       })
  --     end,
  --     desc = "Projects",
  --   },
  --   {
  --     "<leader>fr",
  --     function()
  --       Snacks.picker.recent()
  --     end,
  --     desc = "Recent",
  --   },
  --   -- git
  --   -- {
  --   --   "<leader>gb",
  --   --   function()
  --   --     Snacks.picker.git_branches()
  --   --   end,
  --   --   desc = "Git Branches",
  --   -- },
  --   {
  --     "<leader>gl",
  --     function()
  --       Snacks.picker.git_log()
  --     end,
  --     desc = "Git Log",
  --   },
  --   {
  --     "<leader>gL",
  --     function()
  --       Snacks.picker.git_log_line()
  --     end,
  --     desc = "Git Log Line",
  --   },
  --   {
  --     "<leader>gs",
  --     function()
  --       Snacks.picker.git_status()
  --     end,
  --     desc = "Git Status",
  --   },
  --   {
  --     "<leader>gS",
  --     function()
  --       Snacks.picker.git_stash()
  --     end,
  --     desc = "Git Stash",
  --   },
  --   {
  --     "<leader>gd",
  --     function()
  --       Snacks.picker.git_diff()
  --     end,
  --     desc = "Git Diff (Hunks)",
  --   },
  --   {
  --     "<leader>gf",
  --     function()
  --       Snacks.picker.git_log_file()
  --     end,
  --     desc = "Git Log File",
  --   },
  --   -- Grep
  --   {
  --     "<leader>sb",
  --     function()
  --       Snacks.picker.lines()
  --     end,
  --     desc = "Buffer Lines",
  --   },
  --   {
  --     "<leader>sB",
  --     function()
  --       Snacks.picker.grep_buffers()
  --     end,
  --     desc = "Grep Open Buffers",
  --   },
  --   {
  --     "<leader>sw",
  --     function()
  --       Snacks.picker.grep_word()
  --     end,
  --     desc = "Visual selection or word",
  --     mode = { "n", "x" },
  --   },
  --   -- search
  --   {
  --     "<leader>sc",
  --     function()
  --       Snacks.picker.command_history()
  --     end,
  --     desc = "Command History",
  --   },
  --   {
  --     "<leader>sC",
  --     function()
  --       Snacks.picker.commands()
  --     end,
  --     desc = "Commands",
  --   },
  --   {
  --     "<leader>sd",
  --     function()
  --       Snacks.picker.diagnostics()
  --     end,
  --     desc = "Diagnostics",
  --   },
  --   {
  --     "<leader>sD",
  --     function()
  --       Snacks.picker.diagnostics_buffer()
  --     end,
  --     desc = "Buffer Diagnostics",
  --   },
  --   {
  --     "<leader>sk",
  --     function()
  --       Snacks.picker.keymaps()
  --     end,
  --     desc = "Keymaps",
  --   },
  --   {
  --     "<leader>sp",
  --     function()
  --       Snacks.picker.lazy()
  --     end,
  --     desc = "Search for Plugin Spec",
  --   },
  --   {
  --     "<leader>su",
  --     function()
  --       Snacks.picker.undo()
  --     end,
  --     desc = "Undo History",
  --   },
  --   -- LSP
  --   {
  --     "gd",
  --     function()
  --       Snacks.picker.lsp_definitions({ auto_confirm = true, jump = { reuse_win = true, tagstack = true } })
  --     end,
  --     desc = "Goto Definition",
  --   },
  --   {
  --     "gD",
  --     function()
  --       Snacks.picker.lsp_declarations({ auto_confirm = true, jump = { reuse_win = true, tagstack = true } })
  --     end,
  --     desc = "Goto Declaration",
  --   },
  --   {
  --     "gr",
  --     function()
  --       Snacks.picker.lsp_references({ auto_confirm = true, jump = { reuse_win = true, tagstack = true } })
  --     end,
  --     nowait = true,
  --     desc = "References",
  --   },
  --   {
  --     "gi",
  --     function()
  --       Snacks.picker.lsp_implementations({ auto_confirm = true, jump = { reuse_win = true, tagstack = true } })
  --     end,
  --     desc = "Goto Implementation",
  --   },
  --   {
  --     "gy",
  --     function()
  --       Snacks.picker.lsp_type_definitions({ auto_confirm = true, jump = { reuse_win = true, tagstack = true } })
  --     end,
  --     desc = "Goto T[y]pe Definition",
  --   },
  --   {
  --     "<leader>ss",
  --     function()
  --       Snacks.picker.lsp_symbols({ auto_confirm = true, jump = { reuse_win = true, tagstack = true } })
  --     end,
  --     desc = "LSP Symbols",
  --   },
  --   {
  --     "<leader>sS",
  --     function()
  --       Snacks.picker.lsp_workspace_symbols({ auto_confirm = true, jump = { reuse_win = true, tagstack = true } })
  --     end,
  --     desc = "LSP Workspace Symbols",
  --   },
  -- },
}
